# Generated by Django 5.1.1 on 2024-10-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
